[build]
  command = "pnpm run build"
  # Ensure publish dir points to Next.js build output (not static export "out")
  publish = ".next"

# Enable Next.js Runtime
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["sharp"]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"