[build]
  command = "pnpm run build"

# Enable Next.js Runtime
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["sharp"]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"